[project]
name = "Notes"

[build]
services = ["backend", "frontend"]

[[services]]
name = "backend"
type = "web"
build = "Dockerfile.django"
port = 8000

[[services]]
name = "frontend"
type = "web"
build = "Dockerfile.vite"
port = 3000
